Traceback (most recent call last):
  File "crop_videos.py", line 158, in <module>
    interesting_sections=pd.read_csv("visits_point_mai.csv", sep=";")
  File "/project/166600234/sophie/our_virtual_envs/dlc/venv/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/project/166600234/sophie/our_virtual_envs/dlc/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/project/166600234/sophie/our_virtual_envs/dlc/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/project/166600234/sophie/our_virtual_envs/dlc/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/project/166600234/sophie/our_virtual_envs/dlc/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/project/166600234/sophie/our_virtual_envs/dlc/venv/lib/python3.8/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'visits_point_mai.csv'
